### ISSUE TITLE
clean up ampersands appearing as &amp; in titles

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/research-repository#15]
Looks like maybe titles are being escaped twice? 
e.g. title before [this section](http://research.mysociety.org/sites/who-benefits/l/8.2269.z9un3.p-x9i.lk3ht.v2ukf) renders/reads as

    Affluent Countries: The US &amp; UK

...but note ampersands elsewhere in the running text are appearing OK (yay).

<img width="832" alt="screen shot 2017-08-01 at 15 41 34" src="https://user-images.githubusercontent.com/111320/28830991-4d9f38dc-76d0-11e7-94a4-88e9fe4bd64b.png">

I'm raising this as an issue here _just in case_ it's a consequence of your autoconversion process that I _think_ was used to generate that (wonderful) page; it might just be a thing to fix in that one document, I dunno, in which case sorry for polluting the wrong repo with an issue.

**Comment by ajparsons** [comment]
Resolved! Titles weren't being marked as safe for display.
