### ISSUE TITLE
Problems with FixMyBlock discovery report listing

### ISSUE THREAD

**Issue by zarino** [mysociety/research-repository#28]
1. The "Contents" links on https://research.mysociety.org/publications/fixmyblock-issue-reporting-tower-blocks-discovery lead to URLs like `https://research.mysociety.org/sites/fixmyblock-discovery/#background` which are a 404.
2. The pale blue summary box in the "Tower block safety and the law" section of https://research.mysociety.org/html/fixmyblock-discovery/l/5.9256.6ivu3.7jhzg.hsiey.5w_z- is a duplicate of the previous blue summary box about "Data on tower blocks in the UK".

**Comment by ajparsons** [comment]
Both fixed (the link above re-routes itself to the correct location for that copy).
