### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by sagepe** [mysociety/research-repository#32]
We're using Django 1.11, this went EOL on April 1st, so we need to upgrade.

The current LTS, 2.2, is supported until 2022 and seems like a reasonable target.

**Comment by sagepe** [comment]
We should be targetting 3.2 LTS now.

**Comment by ajparsons** [comment]
I was thinking about this alongside our discussion from the retreat, and that I should be able to pull lots of the related needs from how CAPE is set up.

**Comment by sagepe** [comment]
Also might be worth looking Noiseworks and Labour Mapit as well.

**Comment by sagepe** [comment]
This has been completed, we're now running 3.2.13.
