### ISSUE TITLE
Server Error (500) showing under Related Research heading in Access to Nature Prototyping Report

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/research-repository#52]
Under the "Related Research" heading, at the bottom of the page at:

https://research.mysociety.org/html/prototyping-nature/

I currently see:

>Server Error (500)

It's trying to embed 

https://research.mysociety.org/embed/related:prototyping-nature-test-2

rather than, I assume: 

https://research.mysociety.org/embed/related:prototyping-nature

**Comment by ajparsons** [comment]
Opps, fixed!
